#! /bin/bash

#
# Example script.
#

# Init toolset
rootDir="$(dirname "$0")"
source "${rootDir}/../helpers/Loader.func"

# Script variables


# Base functions


# Greet the user
getGreeting

# Check if this script is run as root
checkSudo
